// Generated by CoffeeScript 1.8.0
(function() {
  var parseMessage, parseQuery, parseUrl, postRequest, promise, url;

  url = require('url');

  promise = require('bluebird');

  module.exports.parseUrl = parseUrl = function(givenUrl) {
    var parsedurl;
    parsedurl = url.parse(givenUrl, true);
    return parsedurl;
  };

  module.exports.parseMessage = parseMessage = function(message) {
    var parser;
    parser = require('packet').createParser();
    return new promise((function(_this) {
      return function(fulfill, reject) {
        parser.extract("l32 =>size", function(record) {
          var data, size;
          size = record.size;
          data = message.toString('utf-8', 4, size);
          return fulfill(JSON.parse(data));
        });
        return parser.parse(message);
      };
    })(this));
  };

  module.exports.postRequest = postRequest = function(body, url) {
    return new promise((function(_this) {
      return function(fulfill, reject) {
        var http, options, parsedurl, req;
        parsedurl = parseUrl(url);
        options = {
          host: parsedurl.hostname,
          port: parsedurl.port,
          path: parsedurl.pathname,
          method: 'POST',
          headers: {
            'content-Type': "application/json"
          }
        };
        console.log("Debug: util: options for http post req are ", options);
        http = require('http');
        req = http.request(options, function(res) {
          if (res.statusCode !== 200) {
            return reject(new Error("Failed with status code " + res.statusCode));
          }
          res.on('data', function(data) {
            return console.log("Response for POST is ", data);
          });
          res.on('error', function(error) {
            console.log("Error: USG notification failed due to " + error);
            return reject(error);
          });
          return res.on('end', function() {
            return fulfill("success");
          });
        });
        req.on('error', function(error) {
          return reject(error);
        });
        if (body) {
          req.write(JSON.stringify(body));
        }
        return req.end();
      };
    })(this));
  };

  module.exports.parseQuery = parseQuery = function(query) {
    var querystring;
    querystring = require('querystring');
    return querystring.parse(query);
  };

}).call(this);
