// Generated by CoffeeScript 1.8.0
(function() {
  var Analyzer, agent, argv, config, storm;

  Analyzer = require('./controllers/analyzer');

  if (require.main === module) {
    argv = require('minimist')(process.argv.slice(2));
    if (argv.h != null) {
      console.log("-h view this help\n-p port number\n-l logfile\n-d datadir");
      return;
    }
    config = require('../package.json').config;
    storm = null;
    agent = new Analyzer(config);
    agent.run(storm);
  }

}).call(this);
