// Generated by CoffeeScript 1.7.1
(function() {
  var Analyzer, agent, argv, config, storm, _ref, _ref1, _ref2;

  Analyzer = require('./controllers/analyzer');

  if (require.main === module) {
    argv = require('minimist')(process.argv.slice(2));
    if (argv.h != null) {
      console.log("-h view this help\n-p port number\n-l logfile\n-d datadir");
      return;
    }
    config = {};
    config.port = (_ref = argv.p) != null ? _ref : 9000;
    config.logfile = (_ref1 = argv.l) != null ? _ref1 : "/tmp/log/analyzer.log";
    config.edb = {
      loglevel: 'trace'
    };
    config.datadir = (_ref2 = argv.d) != null ? _ref2 : "/tmp";
    storm = null;
    agent = new Analyzer(config);
    agent.run(storm);
  }

}).call(this);
