// Generated by CoffeeScript 1.7.1
(function() {
  this.include = function() {
    var agent;
    agent = this.settings.agent;
    this.post({
      '/analyzers': function() {
        return agent.addEventService(this.body).then((function(_this) {
          return function(service) {
            return _this.send(service);
          };
        })(this), (function(_this) {
          return function(error) {
            return _this.next(error);
          };
        })(this));
      }
    });
    this.get({
      '/analyzers/:id': function() {
        var match;
        match = agent.aservices.get(this.params.id);
        if (match !== void 0) {
          return this.send(match);
        } else {
          return this.send(404);
        }
      }
    });
    this.get({
      '/analyzers': function() {
        return this.send(agent.aservices.list());
      }
    });
    this.put({
      '/analyzers/:id': function() {
        return agent.updateEventService(this.params.id, this.body).then((function(_this) {
          return function(service) {
            return _this.send(service);
          };
        })(this), (function(_this) {
          return function(error) {
            return _this.next(error);
          };
        })(this));
      }
    });
    this["delete"]({
      '/analyzers/:id': function() {
        agent.aservices.remove(this.params.id);
        return this.send(204);
      }
    });
    return this.get({
      '/analyzers/:id/stats': function() {
        return agent.getStats(this.params.id, this.query).then(response)((function(_this) {
          return function() {
            return _this.send(response);
          };
        })(this), (function(_this) {
          return function(error) {
            return _this.next(error);
          };
        })(this));
      }
    });
  };

}).call(this);
