// Generated by CoffeeScript 1.7.1
(function() {
  var AnalyzerManager, AnalyzerService, AnalyzerServices, EA, EM, MM, SA, SD, SR, async, bunyan, parseMessage, parseurl, promise, uuid, validate,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  promise = require('bluebird');

  bunyan = require('bunyan');

  EM = require('./elasticmanager');

  MM = require('./mqmanager');

  validate = require('json-schema').validate;

  uuid = require('node-uuid');

  async = require('async');

  SR = require('stormagent').StormRegistry;

  SD = require('stormagent').StormData;

  SA = require('stormagent');

  EA = require('./eventanalyzers');

  parseurl = require('../helpers/utils').parseUrl;

  parseMessage = require('../helpers/utils').parseMessage;

  AnalyzerService = (function(_super) {
    var schema;

    __extends(AnalyzerService, _super);

    schema = {
      name: "AnalyzerService",
      type: "object",
      required: true,
      additionalProperties: true,
      properties: {
        id: {
          "type": "string",
          "required": false
        },
        name: {
          "type": "string",
          "required": false
        },
        output: {
          "type": "string",
          "required": true
        },
        transmitters: {
          "type": "array",
          "required": true
        },
        sources: {
          "type": "array",
          "required": true
        }
      }
    };

    function AnalyzerService(id, data) {
      AnalyzerService.__super__.constructor.call(this, id, data, schema);
      this.em = promise.promisifyAll(EM.prototype);
      this.log("Debug: Elastic manager object is ", this.em);
      this.mq = new MM;
      this.ea = new EA;
      this.susbscriptions = {};
      this.topics = [];
      this.mqConnect();
      this.dbConnect();
    }

    AnalyzerService.prototype.mqConnect = function() {
      if (this.data && (this.data.sources != null)) {
        return this.data.sources.map((function(_this) {
          return function(source) {
            var connect, parsedurl;
            parsedurl = parseurl(source);
            if ((parsedurl.query != null) && (parsedurl.query.topic != null)) {
              parsedurl.query.topic.map(function(topic) {
                return _this.topics.push(topic);
              });
            }
            connect = function() {
              return _this.mq.connect(parsedurl.hostname, parsedurl.port, parsedurl.username, parsedurl.password, 10000, 5);
            };
            _this.mq.on('mq.connected', function(client) {
              _this.log("Connected to the MQ broker", data.sources);
              _this.mqclient = client;
              return _this.subscribe();
            });
            return _this.mq.on('mq.error', function(error) {
              _this.mqclient = "";
              _this.subscriptions = {};
              _this.log("MQ connection failure after multiple retries. Error is " + error);
              _this.log("Retrying connection to MQ in 100 seconds");
              return setTimeout(connect, 100000);
            });
          };
        })(this));
      }
    };

    AnalyzerService.prototype.dbConnect = function() {
      var parsedurl;
      if (this.data && (this.data.output != null)) {
        parsedurl = parseurl(this.data.output);
        this.log("Elastic DB server details: ", parsedurl);
        this.eclient = this.em.init({
          host: parsedurl.host,
          loglevel: 'error'
        });
        return this.log("Connected to the Elasticsearch DB", this.data.output);
      }
    };

    AnalyzerService.prototype.subscribe = function() {
      return this.topics.map((function(_this) {
        return function(topic) {
          switch (topic) {
            case 'LOGGER.SYSLOG':
            case 'logger.syslog':
              return _this.subscriptions[topic] = _this.subscribe("/topic/" + topic, _this.loggersyslog);
          }
        };
      })(this));
    };

    AnalyzerService.prototype.loggersyslog = function(message) {
      var bodykey, data, msg, objkey, str, strarray, syslog, _i, _len;
      this.log("Message from MQ ..check if its in string format or raw buffer.. Assuming buffer format");
      this.log(message);
      msg = this.ea.stripHeader(message.body);
      syslog = this.ea.decodeBinarySyslog(msg);
      switch (syslog.format) {
        case 'email.virus':
        case 'EMAIL.VIRUS':
          return this.ea.emailvirus(syslog).then((function(_this) {
            return function(body) {
              body.id = _this.id;
              _this.mailvirus(body);
              message.ack();
            };
          })(this));
        default:
          data = syslog.message;
          strarray = data.format.split(".");
          bodykey = strarray.pop();
          objkey = "";
          for (_i = 0, _len = strarray.length; _i < _len; _i++) {
            str = strarray[_i];
            objkey += str;
          }
          objkey = objkey.toLowerCase();
          bodykey = bodykey.toLowerCase();
          return this.getTransaction().then((function(_this) {
            return function(content) {
              var b, contentvalue, _base, _base1, _base2, _base3, _name, _name1;
              if ((_base = content._source).transactions == null) {
                _base.transactions = {};
              }
              if ((_base1 = content._source).timestamp == null) {
                _base1.timestamp = data.start;
              }
              if ((_base2 = content._source.transactions)[_name = b = objkey] == null) {
                _base2[_name] = {};
              }
              contentvalue = content._source.transactions[b = objkey];
              if ((_base3 = contentvalue)[_name1 = b = bodykey] == null) {
                _base3[_name1] = 0;
              }
              contentvalue[b = bodykey] += data.count;
              return _this.updateTransaction(content._id, content._source).then(function(result) {
                return message.ack();
              }, function(error) {
                _this.log("Debug: Error in updating the transaction", error, content._source);
                return message.ack();
              });
            };
          })(this), (function(_this) {
            return function(error) {
              var b, content, contentvalue, transaction, _base, _base1, _name, _name1;
              if ((_base = (transaction = {}))[_name = b = bodykey] == null) {
                _base[_name] = {};
              }
              contentvalue = transaction[b = bodykey];
              if ((_base1 = contentvalue)[_name1 = b = bodykey] == null) {
                _base1[_name1] = 0;
              }
              contentvalue[b = bodykey] = data.count;
              content = {
                id: _this.id,
                timestamp: data.start,
                transactions: transaction
              };
              return _this.createTransaction(content).then(function(result) {
                return message.ack();
              }, function(error) {
                _this.log(" Failed to create a transaction record in Elastic search", error, content);
              });
            };
          })(this));
      }
    };

    AnalyzerService.prototype.mailvirus = function(emailData) {
      return this.eclient.createDocumentAsync(this.id, 'email.virus', emailData).then(function(response) {
        return this.log("Added email virus ", response);
      }, function(error) {
        return this.log("Error while adding email virus into elastic DB", error);
      });
    };

    AnalyzerService.prototype.createTransaction = function(content) {
      return this.eclient.ceateDocument(this.eclient, this.id, 'transaction.summary', content).then(function(result) {
        return this.log('added transaction summary record with content', content);
      }, function(error) {
        return this.log('error in adding transaction record', error);
      });
    };

    AnalyzerService.prototype.updateTransaction = function(id, content) {
      return this.eclient.updateDocument(this.eclient, this.id, 'transaction.summary', content).then(function(result) {
        return this.log('updated transaction summary with content', content);
      }, function(error) {
        return this.log("error in updating the transaction with id " + id, error);
      });
    };

    AnalyzerService.prototype.getTransaction = function() {
      var body;
      body = {
        query: {
          filtered: {
            query: {
              match_all: {}
            },
            filter: {
              range: {
                timestamp: {
                  gte: "now/d"
                }
              }
            }
          }
        }
      };
      return new promise((function(_this) {
        return function(fulfill, reject) {
          return _this.eclient.search(_this.eclient, _this.id, 'transaction.summary', body).then(function(results) {
            if (results.length > 1) {
              _this.log("Warning More search results.", results);
              return fulfill(results[0]);
            }
          }, function(error) {
            return reject(error);
          });
        };
      })(this));
    };

    AnalyzerService.prototype.getStats = function(from, to, interval) {
      if (interval == null) {
        interval = '1d';
      }
      switch (interval) {
        case 'month':
          interval = '1m';
          break;
        case 'day':
          interval = '1d';
          break;
        case 'year':
          interval = '1y';
      }
      if (from == null) {
        from = '2014-01-01';
      }
      if (to == null) {
        to = new Date();
      }
      return new promise((function(_this) {
        return function(fulfill, reject) {
          var body;
          body = {
            aggregations: {
              stats: {
                date_historgram: {
                  field: "timestamp",
                  interval: interval,
                  format: 'yyyy-mm-dd',
                  extended_bounds: {
                    min: from,
                    max: to
                  }
                },
                aggs: {
                  webVirusTransactions: {
                    sum: {
                      field: "transactions.webvirus.transactions"
                    }
                  },
                  webVirusViolations: {
                    sum: {
                      field: "transactions.webvirus.violations"
                    }
                  },
                  webContentFilteringTransactions: {
                    sum: {
                      field: "transactions.webcontentfiltering.transactions"
                    }
                  },
                  webContentFilteringViolations: {
                    sum: {
                      field: "transactions.webcontentfiltering.violations"
                    }
                  },
                  mailVirusTransactions: {
                    sum: {
                      field: "transactions.mailvirus.transactions"
                    }
                  },
                  mailVirusViolations: {
                    sum: {
                      field: "transactions.mailvirus.violations"
                    }
                  }
                }
              }
            }
          };
          return _this.em.searchAsync(_this.eclient, _this.id, 'transaction.summary', body).then(function(results) {
            return fulfill(results);
          }, function(error) {
            return reject(error);
          });
        };
      })(this));
    };

    return AnalyzerService;

  })(SD);

  AnalyzerServices = (function(_super) {
    __extends(AnalyzerServices, _super);

    function AnalyzerServices(filename) {
      this.on('load', function(key, val) {
        var entry;
        entry = new AnalyzerService(key, val);
        if (entry != null) {
          entry.saved = true;
          return this.add(key, entry);
        }
      });
      this.on('removed', function(key) {});
      AnalyzerServices.__super__.constructor.call(this, filename);
    }

    AnalyzerServices.prototype.get = function(key) {
      var entry;
      entry = AnalyzerServices.__super__.get.call(this, key);
      if (!((entry != null) && (entry.data != null))) {
        return;
      }
      entry.data.id = entry.id;
      return entry.data;
    };

    AnalyzerServices.prototype.getEntry = function(key) {
      if (!key) {
        return;
      }
      return this.entries[key];
    };

    AnalyzerServices.prototype.add = function(key, entry) {
      if (!((entry != null) && (entry.data != null))) {
        return;
      }
      entry.data.id = entry.id;
      return AnalyzerServices.__super__.add.call(this, key, entry);
    };

    return AnalyzerServices;

  })(SR);

  AnalyzerManager = (function(_super) {
    __extends(AnalyzerManager, _super);

    function AnalyzerManager(config) {
      AnalyzerManager.__super__.constructor.call(this, config);
      this.config = config;
      this["import"](module);
    }

    AnalyzerManager.prototype.run = function(config) {
      AnalyzerManager.__super__.run.call(this, config);
      this.log("data dir is ", this.config);
      return this.aservices = new AnalyzerServices("" + this.config.datadir + "/analyzerservices.db");
    };

    AnalyzerManager.prototype.addEventService = function(service) {
      this.log("rcvd service", service);
      return new promise((function(_this) {
        return function(fulfill, reject) {
          var aservice, err;
          try {
            aservice = new AnalyzerService(null, service);
          } catch (_error) {
            err = _error;
            _this.log("error is ", err);
            return reject(new Error(err));
          }
          _this.aservices.add(aservice.id, aservice);
          return fulfill(aservice.data);
        };
      })(this));
    };

    AnalyzerManager.prototype.updateEventService = function(id, service) {
      console.log("rcvd contents", "id: " + id, "entry: ", service);
      return new promise((function(_this) {
        return function(fulfill, reject) {
          var aservice, entry, err;
          try {
            aservice = new AnalyzerService(id, service);
          } catch (_error) {
            err = _error;
            return reject(new Error(err));
          }
          entry = _this.aservices.update(aservice.id, aservice);
          return fulfill(entry);
        };
      })(this));
    };

    AnalyzerManager.prototype.getStats = function(id, params) {
      var entry;
      entry = this.aservices.getEntry(id);
      return entry.getStats(params.from, params.to, params.interval);
    };

    AnalyzerManager.prototype.dummyHandler = function(message) {
      console.log("recvd message form ActiveMQ", message);
      if (message) {
        return message.ack();
      }
    };

    return AnalyzerManager;

  })(SA);

  module.exports = AnalyzerManager;

}).call(this);
