// Generated by CoffeeScript 1.7.1
(function() {
  var EventAnalyzer, packet;

  packet = require('packet');

  EventAnalyzer = (function() {
    function EventAnalyzer() {}

    EventAnalyzer.prototype.handler = function() {};

    return EventAnalyzer;

  })();

  module.exports = EventAnalyzer;

}).call(this);
